[package]
name = "g3proxy-ctl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
clap = "4.0"
clap_complete = "4.0"
tokio = { version = "1.0", features = ["rt", "net", "macros", "io-util", "fs"] }
tokio-util = { version = "0.7", features = ["compat"] }
futures-util = "0.3"
capnp-rpc = "0.16"
capnp = "0.16"
serde_json = "1.0"
g3proxy-proto = { path = "../../proto" }
g3-types = { path = "../../../lib/g3-types", features = ["resolve"] }
