[package]
name = "test-copy-yield"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.23", features = ["time", "macros", "rt"] }
g3-io-ext = { path = "../../lib/g3-io-ext" }
