[package]
name = "g3bench"
version = "0.6.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
once_cell = "1.7"
clap = "4.0"
clap_complete = "4.0"
async-trait = "0.1"
indicatif = "0.17"
tokio = { version = "1.0", features = ["rt", "net", "macros"] }
http = "0.2"
url = "2.1"
h2 = "0.3"
bytes = "1.0"
futures-util = "0.3"
tokio-openssl = "0.6"
openssl = "0.10"
cadence = { package = "cadence-with-flush", version = "0.29" }
hdrhistogram = "7.5"
ahash = "0.8"
g3-runtime = { path = "../lib/g3-runtime" }
g3-signal = { path = "../lib/g3-signal" }
g3-types = { path = "../lib/g3-types", features = ["proxy"] }
g3-clap = { path = "../lib/g3-clap" }
g3-socket = { path = "../lib/g3-socket" }
g3-http = { path = "../lib/g3-http" }
g3-socks = { path = "../lib/g3-socks" }
g3-io-ext = { path = "../lib/g3-io-ext" }
g3-statsd = { path = "../lib/g3-statsd" }

[build-dependencies]
rustc_version = "0.4"

[features]
default = []
vendored-openssl = ["openssl/vendored"]
