[package]
name = "g3proxy-ftp"
version = "0.1.0"
license.workspace = true
edition.workspace = true
rust-version = "1.59.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
tokio = { workspace = true, features = ["rt", "net", "macros", "io-std", "io-util", "fs"] }
clap.workspace = true
clap_complete.workspace = true
async-trait.workspace = true
log = { workspace = true, features = ["max_level_debug", "release_max_level_debug"] }
g3-types.workspace = true
g3-socket.workspace = true
g3-ftp-client = { workspace = true, features = ["log-raw-io"] }
